###
GET http://localhost:4004/odata/v4/nautical/MAS




###
POST  http://localhost:4004/odata/v4/nautical/MAS
Content-Type: application/json

{
    "BNAME":"JIBIN",
    "CODE" :"CLASS",
     "VALUE":"CLASS OF VESSEL",
     "CVALUE":"INR" ,
     "CUNIT":"CUNIT",  
     "DATATYPE":"DAT",
     "TABLENAME":"TABLENAME",
     "MULTI_CHOICE":true
}
###
DELETE  http://localhost:4004/odata/v4/nautical/NAVOYGIP/

###
PATCH   http://localhost:4004/odata/v4/nautical/NAVOYGIP/VOY2
Content-Type: application/json

{

"PORTN": "PCity"

}